---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the php packages (APT)
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items: "{{ php7_fpm_apt_packages }}"
  environment: "{{ env }}"
  when: ansible_os_family == "Debian"
  notify:
     - restart php7-fpm
  tags: [packages,php,fpm]

- name: Copy the PHP configuration file
  ini_file: >
    dest={{ php7_fpm_ini_path }}
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
    backup=yes
  with_items: "{{ php7_fpm_ini }}"
  notify:
   - restart php7-fpm
  tags: [configuration,php,fpm]

- name: Copy the FPM configuration
  ini_file: >
    dest={{ php7_fpm_config_path }}
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
    backup=yes
  with_items: "{{ php7_fpm_config }}"
  register: copy_fpm_config
  notify:
   - restart php7-fpm
  tags: [configuration,php,fpm]

- name: Delete the include line from the ini file
  ini_file: >
    dest={{ php7_fpm_config_path }}
    section=global
    option=include
    state=absent
    backup=no
  when: copy_fpm_config.changed
  notify:
   - restart php7-fpm
  tags: [configuration,php,fpm]

- name: Readd the include line to the ini file
  ini_file: >
    dest={{ php7_fpm_config_path }}
    section=global
    option=include
    value="{{ php7_fpm_pool_d }}/*.conf"
    state=present
    backup=no
  when: copy_fpm_config.changed
  notify:
   - restart php7-fpm
  tags: [configuration,php,fpm]

- name: Delete the default POOL configuration file
  file: >
    path={{ php7_fpm_pool_d }}/{{ php7_fpm_default_pool.name }}
    state=absent
  when: php7_fpm_default_pool.delete
  tags: [configuration,php,fpm]

- name: Copy the POOL configurations
  template: >
    src=pool.conf.j2
    dest={{ php7_fpm_pool_d }}/{{ item['name'] }}.conf
    backup=yes
  with_items: "{{ php7_fpm_pools }}"
  when: php7_fpm_pools|lower != 'none'
  notify:
   - restart php7-fpm
  tags: [configuration,php,fpm]

- name: Check php7-fpm syntax of configuration files
  shell: "{{ php7_fpm_binary_name }} -t"
  register: result
  changed_when: "result.rc != 0"
  tags: [configuration,php,fpm]

- name: Start the php{{ php7_fpm_version }}-fpm service
  service: name={{ php7_fpm_service_name }} state=started enabled=yes
  tags: [service,php,fpm]
